services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis/redis-stack:latest'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - '6379'
